version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: yourdbname
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword

  web:
    build: .
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=django-insecure-3n7x3xs1u+e(z$e(x!m&p2$w2$2#+%s)@($_4$d7cog-n+(j8o
      - DEBUG=True
      - ALLOWED_HOSTS=*
      - DB_HOST=db
      - DB_NAME=yourdbname
      - DB_USER=youruser
      - DB_PASS=yourpassword
    depends_on:
      - db
